// Lib index - Tüm lib dosyalarını tek yerden export et

// Mock data
export * from './mockData';

// API template
export * from './apiTemplate';

// Auth utilities
export * from './authUtils';

// Query client
export * from './queryClient';

// General utilities
export * from './utils';

// Re-export commonly used utilities with shorter names
export { mockUser, mockCompanies, mockLocations, mockModems, mockSimCards, mockWorkOrders, mockTestScenarios, mockTestSessions, mockScrapRequests, mockAlerts, mockActivityLogs, mockStats, performMockSearch } from './mockData';

export { 
  API_CONFIG, 
  apiClient, 
  setAuthToken, 
  getAuthToken, 
  removeAuthToken, 
  isAuthenticated, 
  API_ENDPOINTS, 
  handleApiError,
  addRequestInterceptor,
  addResponseInterceptor
} from './apiTemplate';

export type { 
  ApiResponse, 
  PaginatedResponse 
} from './apiTemplate';

export { 
  loginUser, 
  logoutUser, 
  refreshToken, 
  getUserProfile 
} from './authUtils';

export { 
  queryClient, 
  QueryClientProvider 
} from './queryClient';

export { 
  cn, 
  formatDate, 
  formatCurrency, 
  generateId, 
  debounce, 
  throttle,
  isValidEmail,
  isValidPhone,
  isValidIMEI,
  isValidICCID,
  formatFileSize,
  formatDuration,
  formatPercentage,
  formatNumber,
  formatDateTime,
  parseDate,
  validateRequired,
  validateMinLength,
  validateMaxLength,
  validatePattern,
  validateRange,
  validateCustom,
  validateForm,
  showSuccessToast,
  showErrorToast,
  showWarningToast,
  showInfoToast,
  confirmDialog,
  promptDialog,
  downloadFile,
  uploadFile,
  copyToClipboard,
  openInNewTab,
  scrollToElement,
  focusElement,
  getElementPosition,
  isElementInViewport,
  addEventListener,
  removeEventListener,
  dispatchCustomEvent,
  getQueryParams,
  setQueryParams,
  removeQueryParams,
  clearQueryParams,
  getLocalStorage,
  setLocalStorage,
  removeLocalStorage,
  clearLocalStorage,
  getSessionStorage,
  setSessionStorage,
  removeSessionStorage,
  clearSessionStorage,
  getCookie,
  setCookie,
  removeCookie,
  clearCookies,
  isOnline,
  isOffline,
  getNetworkInfo,
  getDeviceInfo,
  getBrowserInfo,
  getOSInfo,
  getScreenInfo,
  getWindowInfo,
  getLocationInfo,
  getTimezoneInfo,
  getLanguageInfo,
  getCurrencyInfo,
  getDateFormatInfo,
  getNumberFormatInfo,
  getTimeFormatInfo,
  getMeasurementInfo,
  getTemperatureInfo,
  getWeightInfo,
  getLengthInfo,
  getVolumeInfo,
  getAreaInfo,
  getSpeedInfo,
  getPressureInfo,
  getEnergyInfo,
  getPowerInfo,
  getFrequencyInfo,
  getAngleInfo,
  getDataInfo,
  getDigitalInfo,
  getAnalogInfo,
  getSignalInfo,
  getQualityInfo,
  getStrengthInfo,
  getLevelInfo,
  getStatusInfo,
  getConditionInfo,
  getHealthInfo,
  getPerformanceInfo,
  getEfficiencyInfo,
  getReliabilityInfo,
  getAvailabilityInfo,
  getMaintainabilityInfo,
  getSafetyInfo,
  getSecurityInfo,
  getPrivacyInfo,
  getComplianceInfo,
  getRegulatoryInfo,
  getStandardInfo,
  getProtocolInfo,
  getInterfaceInfo,
  getConnectionInfo,
  getNetworkInfo as getNetworkDetails,
  getDeviceInfo as getDeviceDetails,
  getBrowserInfo as getBrowserDetails,
  getOSInfo as getOSDetails,
  getScreenInfo as getScreenDetails,
  getWindowInfo as getWindowDetails,
  getLocationInfo as getLocationDetails,
  getTimezoneInfo as getTimezoneDetails,
  getLanguageInfo as getLanguageDetails,
  getCurrencyInfo as getCurrencyDetails,
  getDateFormatInfo as getDateFormatDetails,
  getNumberFormatInfo as getNumberFormatDetails,
  getTimeFormatInfo as getTimeFormatDetails,
  getMeasurementInfo as getMeasurementDetails,
  getTemperatureInfo as getTemperatureDetails,
  getWeightInfo as getWeightDetails,
  getLengthInfo as getLengthDetails,
  getVolumeInfo as getVolumeDetails,
  getAreaInfo as getAreaDetails,
  getSpeedInfo as getSpeedDetails,
  getPressureInfo as getPressureDetails,
  getEnergyInfo as getEnergyDetails,
  getPowerInfo as getPowerDetails,
  getFrequencyInfo as getFrequencyDetails,
  getAngleInfo as getAngleDetails,
  getDataInfo as getDataDetails,
  getDigitalInfo as getDigitalDetails,
  getAnalogInfo as getAnalogDetails,
  getSignalInfo as getSignalDetails,
  getQualityInfo as getQualityDetails,
  getStrengthInfo as getStrengthDetails,
  getLevelInfo as getLevelDetails,
  getStatusInfo as getStatusDetails,
  getConditionInfo as getConditionDetails,
  getHealthInfo as getHealthDetails,
  getPerformanceInfo as getPerformanceDetails,
  getEfficiencyInfo as getEfficiencyDetails,
  getReliabilityInfo as getReliabilityDetails,
  getAvailabilityInfo as getAvailabilityDetails,
  getMaintainabilityInfo as getMaintainabilityDetails,
  getSafetyInfo as getSafetyDetails,
  getSecurityInfo as getSecurityDetails,
  getPrivacyInfo as getPrivacyDetails,
  getComplianceInfo as getComplianceDetails,
  getRegulatoryInfo as getRegulatoryDetails,
  getStandardInfo as getStandardDetails,
  getProtocolInfo as getProtocolDetails,
  getInterfaceInfo as getInterfaceDetails,
  getConnectionInfo as getConnectionDetails
} from './utils';
