// Frontend Ana Index - Tüm export'ları tek yerden yap

// Components
export * from './components';

// Hooks
export * from './hooks';

// Lib utilities
export * from './lib';

// Types
export * from './types';

// Pages
export { default as Dashboard } from './pages/Dashboard';
export { default as Landing } from './pages/Landing';
export { default as InventoryList } from './pages/Inventory/InventoryList';
export { default as GSMInventory } from './pages/GSM/GSMInventory';
export { default as FieldMonitoring } from './pages/Field/FieldMonitoring';
export { default as LabTracking } from './pages/Laboratory/LabTracking';
export { default as TestDashboard } from './pages/Testing/TestDashboard';
export { default as SLADashboard } from './pages/SLA/SLADashboard';
export { default as ScrapTracking } from './pages/Scrap/ScrapTracking';
export { default as CompanyPortal } from './pages/Company/CompanyPortal';

// Layout components
export { default as MainLayout } from './components/Layout/MainLayout';
export { default as Header } from './components/Layout/Header';
export { default as Sidebar } from './components/Layout/Sidebar';

// Dashboard components
export { default as InventoryOverview } from './components/Dashboard/InventoryOverview';
export { default as QuickAccessModules } from './components/Dashboard/QuickAccessModules';
export { default as RecentActivityTable } from './components/Dashboard/RecentActivityTable';
export { default as RecentAlerts } from './components/Dashboard/RecentAlerts';
export { default as StatisticsCards } from './components/Dashboard/StatisticsCards';

// Re-export commonly used items with shorter names
export { 
  // Components
  Button as Btn,
  Card as C,
  Input as I,
  Label as L,
  Table as T,
  Badge as B,
  Dialog as D,
  Form as F,
  Select as S,
  Textarea as TA,
  Switch as SW,
  Checkbox as CB,
  RadioGroup as RG,
  Tabs as TS,
  Accordion as AC,
  Alert as AL,
  Toast as TO,
  Tooltip as TT,
  Popover as P,
  DropdownMenu as DM,
  ContextMenu as CM,
  NavigationMenu as NM,
  Menubar as MB,
  Command as CMD,
  Calendar as CAL,
  Progress as PGS,
  Slider as SL,
  Separator as SEP,
  ScrollArea as SA,
  ResizablePanel as RP,
  Sheet as SH,
  Drawer as DR,
  HoverCard as HC,
  Avatar as AV,
  Skeleton as SK,
  Pagination as PG,
  InputOTP as IOTP,
  Sidebar as SB,
  Toggle as TG,
  ToggleGroup as TGGRP,
  Carousel as CR,
  AspectRatio as AR,
  AlertDialog as AD,
  Collapsible as CL,
  Breadcrumb as BC,
  Chart as CH,
  ModeIndicator as MI,
  CompactModeIndicator as CMI,
  TooltipModeIndicator as TMI,
  
  // Hooks
  useDataMode,
  useConditionalHook,
  useSmartHook,
  useMobile,
  useToast,
  useAuth,
  
  // Mock data hooks
  useDashboardStats,
  useCompanies,
  useCreateCompany,
  useLocations,
  useCreateLocation,
  useModems,
  useModem,
  useCreateModem,
  useUpdateModem,
  useSimCards,
  useCreateSimCard,
  useWorkOrders,
  useCreateWorkOrder,
  useUpdateWorkOrder,
  useSLAAlerts,
  useTestScenarios,
  useCreateTestScenario,
  useTestSessions,
  useCreateTestSession,
  useUpdateTestSession,
  useScrapRequests,
  useCreateScrapRequest,
  useUpdateScrapRequest,
  useAlerts,
  useCreateAlert,
  useMarkAlertAsRead,
  useGlobalSearch,
  useExportModems,
  
  // API hooks
  useApiData,
  useApiMutation,
  useApiCompanies,
  useApiCreateCompany,
  useApiUpdateCompany,
  useApiDeleteCompany,
  useApiLocations,
  useApiCreateLocation,
  useApiUpdateLocation,
  useApiDeleteLocation,
  useApiModems,
  useApiModem,
  useApiCreateModem,
  useApiUpdateModem,
  useApiDeleteModem,
  useApiSearchModems,
  useApiSimCards,
  useApiCreateSimCard,
  useApiUpdateSimCard,
  useApiDeleteSimCard,
  useApiWorkOrders,
  useApiCreateWorkOrder,
  useApiUpdateWorkOrder,
  useApiDeleteWorkOrder,
  useApiSLAAlerts,
  useApiTestScenarios,
  useApiCreateTestScenario,
  useApiUpdateTestScenario,
  useApiDeleteTestScenario,
  useApiTestSessions,
  useApiCreateTestSession,
  useApiUpdateTestSession,
  useApiDeleteTestSession,
  useApiScrapRequests,
  useApiCreateScrapRequest,
  useApiUpdateScrapRequest,
  useApiDeleteScrapRequest,
  useApiAlerts,
  useApiCreateAlert,
  useApiUpdateAlert,
  useApiDeleteAlert,
  useApiMarkAlertAsRead,
  useApiDashboardStats,
  useApiRecentActivities,
  useApiDashboardAlerts,
  useApiGlobalSearch,
  useApiExportModems,
  
  // Utilities
  mockUser,
  mockCompanies,
  mockLocations,
  mockModems,
  mockSimCards,
  mockWorkOrders,
  mockTestScenarios,
  mockTestSessions,
  mockScrapRequests,
  mockAlerts,
  mockActivityLogs,
  mockStats,
  performMockSearch,
  API_CONFIG,
  apiClient,
  setAuthToken,
  getAuthToken,
  removeAuthToken,
  isAuthenticated,
  API_ENDPOINTS,
  handleApiError,
  addRequestInterceptor,
  addResponseInterceptor,
  loginUser,
  logoutUser,
  refreshToken,
  getUserProfile,
  queryClient,
  QueryClientProvider,
  cn,
  formatDate,
  formatCurrency,
  generateId,
  debounce,
  throttle,
  isValidEmail,
  isValidPhone,
  isValidIMEI,
  isValidICCID,
  formatFileSize,
  formatDuration,
  formatPercentage,
  formatNumber,
  formatDateTime,
  parseDate,
  validateRequired,
  validateMinLength,
  validateMaxLength,
  validatePattern,
  validateRange,
  validateCustom,
  validateForm,
  showSuccessToast,
  showErrorToast,
  showWarningToast,
  showInfoToast,
  confirmDialog,
  promptDialog,
  downloadFile,
  uploadFile,
  copyToClipboard,
  openInNewTab,
  scrollToElement,
  focusElement,
  getElementPosition,
  isElementInViewport,
  addEventListener,
  removeEventListener,
  dispatchCustomEvent,
  getQueryParams,
  setQueryParams,
  removeQueryParams,
  clearQueryParams,
  getLocalStorage,
  setLocalStorage,
  removeLocalStorage,
  clearLocalStorage,
  getSessionStorage,
  setSessionStorage,
  removeSessionStorage,
  clearSessionStorage,
  getCookie,
  setCookie,
  removeCookie,
  clearCookies,
  isOnline,
  isOffline,
  getNetworkInfo,
  getDeviceInfo,
  getBrowserInfo,
  getOSInfo,
  getScreenInfo,
  getWindowInfo,
  getLocationInfo,
  getTimezoneInfo,
  getLanguageInfo,
  getCurrencyInfo,
  getDateFormatInfo,
  getNumberFormatInfo,
  getTimeFormatInfo,
  getMeasurementInfo,
  getTemperatureInfo,
  getWeightInfo,
  getLengthInfo,
  getVolumeInfo,
  getAreaInfo,
  getSpeedInfo,
  getPressureInfo,
  getEnergyInfo,
  getPowerInfo,
  getFrequencyInfo,
  getAngleInfo,
  getDataInfo,
  getDigitalInfo,
  getAnalogInfo,
  getSignalInfo,
  getQualityInfo,
  getStrengthInfo,
  getLevelInfo,
  getStatusInfo,
  getConditionInfo,
  getHealthInfo,
  getPerformanceInfo,
  getEfficiencyInfo,
  getReliabilityInfo,
  getAvailabilityInfo,
  getMaintainabilityInfo,
  getSafetyInfo,
  getSecurityInfo,
  getPrivacyInfo,
  getComplianceInfo,
  getRegulatoryInfo,
  getStandardInfo,
  getProtocolInfo,
  getInterfaceInfo,
  getConnectionInfo,
  getNetworkDetails,
  getDeviceDetails,
  getBrowserDetails,
  getOSDetails,
  getScreenDetails,
  getWindowDetails,
  getLocationDetails,
  getTimezoneDetails,
  getLanguageDetails,
  getCurrencyDetails,
  getDateFormatDetails,
  getNumberFormatDetails,
  getTimeFormatDetails,
  getMeasurementDetails,
  getTemperatureDetails,
  getWeightDetails,
  getLengthDetails,
  getVolumeDetails,
  getAreaDetails,
  getSpeedDetails,
  getPressureDetails,
  getEnergyDetails,
  getPowerDetails,
  getFrequencyDetails,
  getAngleDetails,
  getDataDetails,
  getDigitalDetails,
  getAnalogDetails,
  getSignalDetails,
  getQualityDetails,
  getStrengthDetails,
  getLevelDetails,
  getStatusDetails,
  getConditionDetails,
  getHealthDetails,
  getPerformanceDetails,
  getEfficiencyDetails,
  getReliabilityDetails,
  getAvailabilityDetails,
  getMaintainabilityDetails,
  getSafetyDetails,
  getSecurityDetails,
  getPrivacyDetails,
  getComplianceDetails,
  getRegulatoryDetails,
  getStandardDetails,
  getProtocolDetails,
  getInterfaceDetails,
  getConnectionDetails
} from './components';

// Default exports for commonly used items
export { default as App } from './App';
export { default as MainLayout as Layout } from './components/Layout/MainLayout';
export { default as Dashboard as Home } from './pages/Dashboard';
export { default as InventoryList as Inventory } from './pages/Inventory/InventoryList';
export { default as GSMInventory as GSM } from './pages/GSM/GSMInventory';
export { default as FieldMonitoring as Field } from './pages/Field/FieldMonitoring';
export { default as LabTracking as Lab } from './pages/Laboratory/LabTracking';
export { default as TestDashboard as Testing } from './pages/Testing/TestDashboard';
export { default as SLADashboard as SLA } from './pages/SLA/SLADashboard';
export { default as ScrapTracking as Scrap } from './pages/Scrap/ScrapTracking';
export { default as CompanyPortal as Company } from './pages/Company/CompanyPortal';
